#!/usr/bin/env sh

mode=${1:-"check"}
machine=${2:-$(hostname -s)}

# The base config will always be one level above this script's directory.
CONFIG_PATH=$(dirname "$(dirname "$0")")

/nix/var/nix/profiles/default/bin/nix build \
  --experimental-features 'flakes nix-command' \
  --show-trace \
  --no-link \
  "${CONFIG_PATH}/#${machine}-system"

result=$(
  /nix/var/nix/profiles/default/bin/nix path-info \
    --extra-experimental-features 'flakes nix-command' \
    "${CONFIG_PATH}/#${machine}-system"
)

if [ "$mode" = "check" ]; then
  "${result}"/sw/bin/darwin-rebuild --flake "${CONFIG_PATH}/#${machine}" check
elif [ "$mode" = "switch" ] ; then
  "${result}"/sw/bin/darwin-rebuild --flake "${CONFIG_PATH}/#${machine}" switch
else
  echo "Invalid argument '${mode}'; must be one of 'check' or 'switch'."
  exit
fi
