#!/usr/bin/env sh

mode=${1:-"check"}
machine=${2:-$(hostname -s)}

CONFIG_PATH="${HOME}/.config/dotfiles"

/nix/var/nix/profiles/default/bin/nix build \
  --experimental-features 'flakes nix-command' \
  --show-trace \
  --no-link \
  "${CONFIG_PATH}"/#darwinConfigurations."${machine}".system

result=$(
  /nix/var/nix/profiles/default/bin/nix path-info \
    --extra-experimental-features 'flakes nix-command' \
    "${CONFIG_PATH}"/#darwinConfigurations."${machine}".system
)

if [ "$mode" = "check" ]; then
  "${result}"/sw/bin/darwin-rebuild --flake "${CONFIG_PATH}/#${machine}" check
elif [ "$mode" = "switch" ] ; then
  "${result}"/sw/bin/darwin-rebuild --flake "${CONFIG_PATH}/#${machine}" switch
else
  echo "Invalid argument '${mode}'; must be one of 'check' or 'switch'."
  exit
fi
