#!/usr/bin/env sh

mode=${1:-"check"}
machine=${2:-$(hostname -s)}

# The base config will always be one level above this script's directory.
CONFIG_PATH=$(dirname "$(dirname "$0")")

nix build \
  --experimental-features 'flakes nix-command' \
  --show-trace \
  --no-link \
  "${CONFIG_PATH}/#${machine}-user"

result=$(
  nix path-info \
    --extra-experimental-features 'flakes nix-command' \
    "${CONFIG_PATH}/#${machine}-user"
)

if [ "$mode" = "check" ]; then
  echo "${result}"
elif [ "$mode" = "switch" ] ; then
  "${result}/activate"
else
  echo "Invalid argument '${mode}'; must be one of 'check' or 'switch'."
  exit
fi
